services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fraud_api_container
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
    volumes:
      - ./mlflow.db:/app/mlflow.db
      - ./mlruns:/app/mlruns
    restart: unless-stopped